-- CREATE TABLE public.product (
-- 	product_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
-- 	brand varchar(255) NULL,
-- 	description varchar(255) NULL,
-- 	img varchar(255) NULL,
-- 	is_available bool NOT NULL,
-- 	"name" varchar(255) NULL,
-- 	price numeric(38, 2) NULL,
-- 	quantity int4 NOT NULL,
-- 	release_date timestamp(6) NULL,
-- 	image_name varchar(255) NULL,
-- 	image_data oid NULL,
-- 	image_type varchar(255) NULL,
-- 	category varchar(255) NULL,
-- 	CONSTRAINT product_pkey PRIMARY KEY (product_id)
-- );
-- CREATE TABLE public.categories (
-- 	id int4 NOT NULL,
-- 	"name" varchar(255) NULL,
-- 	CONSTRAINT categories_pkey PRIMARY KEY (id)
-- );

DELETE FROM public.categories;
INSERT INTO public.categories (id,"name") VALUES
	 (1,'Mobiles'),
	 (2,'Laptops'),
	 (3,'Accessories'),
	 (4,'Wearables'),
	 (5,'Electronics');

     DELETE FROM public.products;
INSERT INTO public.product (brand,description,img,is_available,"name",price,quantity,release_date,image_name,image_data,image_type,category) VALUES
	 ('Apple','Latest Apple smartphone',NULL,true,'iPhone 15',79999.00,10,'2024-09-10 05:30:00',NULL,NULL,NULL,'2'),
	 ('Motorola','Less Budget with Bad Camera',NULL,true,'Motorola',12000.00,80,'2026-01-04 05:30:00','Samsung-Mobile-Phone-Free-PNG-Image.png',16690,'image/png','1'),
	 ('Apple','Smooth with good Features',NULL,true,'Macbook',89999.00,2,'2026-01-01 05:30:00','OIP.jpg',16836,'image/jpeg','2'),
	 ('SAMSUNG','GDF',NULL,true,'SAMSUNG',22222.00,4,NULL,'haikyu_wallp.jpg',16837,'image/jpeg','5'),
	 ('Sony','Noise cancelling headphones',NULL,false,'Sony Headphones',2499.00,0,'2023-11-05 05:30:00',NULL,NULL,NULL,'4'),
	 ('Parle','G for Genius',NULL,true,'PARLE-G',5.00,53,NULL,'1588951001-parle-g-gold-biscuits.jpg',16839,'image/jpeg','3');

     UPDATE public.product set image_data =  null where image_data is NOT null;

-- CREATE TABLE IF NOT EXISTS public.users (
-- 	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
-- 	"password" varchar(255) NULL,
-- 	"role" varchar(255) NULL,
-- 	username varchar(255) NULL,
-- 	CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username),
-- 	CONSTRAINT users_pkey PRIMARY KEY (id)
-- );
DELETE from users;
INSERT INTO users ("password","role",username) VALUES
	 ('$2a$12$JCkegVvFcFa.DKq757ltQunepHANWVXbEv8ln8W.CSOjfJu8a2uSC','admin','anuj');
	--  ('$2a$12$WHcLWf7BKyEVsYMYXbAs5uNZS/s50z3yo4UzuMHzhR0cq1bo9n18C','user','rahu2l'),
	--  ('$2a$12$.e2VhVoCJzjPuqTQOdSRaOe8.UO5kPaZinS2U6a4UK5nUWaOyW9b.','user','anuj123'),
	--  ('$2a$12$hvYY9bde0OCIatnCdG5uLO6Sc6AQ8Cw3T9wkFEoPeuT4kpncSJ.wi','user','pratik');


-- CREATE TABLE public.registered_user (
-- 	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
-- 	dob date NULL,
-- 	email varchar(255) NULL,
-- 	first_name varchar(255) NULL,
-- 	last_name varchar(255) NULL,
-- 	phone_number varchar(255) NULL,
-- 	user_id int8 NOT NULL,
-- 	CONSTRAINT registered_user_pkey PRIMARY KEY (id),
-- 	CONSTRAINT uk4qkjfwb01bh3q0r5x8uy5o67v UNIQUE (email),
-- 	CONSTRAINT ukeb66l2mde4qyewvm5jcm5pr1b UNIQUE (user_id),
-- 	CONSTRAINT fkko44yck3yrira7opdg5mwqd6b FOREIGN KEY (user_id) REFERENCES public.users(id)
-- );

-- INSERT INTO public.registered_user (dob,email,first_name,last_name,phone_number,user_id) VALUES
-- 	 ('2000-01-01','anuj@gmail.com','Anuj','Kumar','99304343',6),
-- 	 ('0003-02-23','pratik@gmail.com','pratik','pandey',NULL,7);

-- CREATE TABLE public.cart (
-- 	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
-- 	quantity int4 NOT NULL,
-- 	product_id int4 NOT NULL,
-- 	user_id int8 NOT NULL,
-- 	CONSTRAINT cart_pkey PRIMARY KEY (id),
-- 	CONSTRAINT fk_cart_product FOREIGN KEY (product_id) REFERENCES public.product(product_id),
-- 	CONSTRAINT fkg5uhi8vpsuy0lgloxk2h4w5o6 FOREIGN KEY (user_id) REFERENCES public.users(id)
-- );

-- INSERT INTO public.cart (quantity,product_id,user_id) VALUES
-- 	 (3,1,7),
-- 	 (1,13,5),
-- 	 (1,2,5),
-- 	 (1,2,6),
-- 	 (1,14,5),
-- 	 (2,6,6);
